# Generated by Django 5.0.1 on 2024-02-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaire', '0004_alter_cd_id_alter_dvd_id_alter_emprunteur_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='emprunteur_nom',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur_nom',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur_nom',
        ),
        migrations.AddField(
            model_name='cd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotecaire.emprunteur'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotecaire.emprunteur'),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotecaire.emprunteur'),
        ),
        migrations.AddField(
            model_name='livre',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotecaire.emprunteur'),
        ),
    ]
