# Generated by Django 5.0.1 on 2024-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaire', '0005_remove_cd_emprunteur_nom_remove_dvd_emprunteur_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudeplateau',
            name='dateEmprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
