# Generated by Django 5.0.1 on 2024-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaire', '0006_jeudeplateau_dateemprunt_jeudeplateau_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='disponible',
        ),
    ]
