# Generated by Django 5.0.1 on 2024-02-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaire', '0008_emprunteur_nb_emprunts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='dateEmprunt',
            new_name='date_emprunt',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dateEmprunt',
            new_name='date_emprunt',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='dateEmprunt',
            new_name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='emprunteur',
        ),
    ]
