# Generated by Django 5.0.1 on 2024-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_name', models.CharField(max_length=45)),
                ('cd_artiste', models.CharField(max_length=45)),
                ('cd_dateEmprunt', models.DateField(blank=True, null=True)),
                ('cd_disponible', models.BooleanField(default=True)),
                ('cd_emprunteur_nom', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvd_name', models.CharField(max_length=45)),
                ('dvd_realisateur', models.CharField(max_length=45)),
                ('dvd_dateEmprunt', models.DateField(blank=True, null=True)),
                ('dvd_disponible', models.BooleanField(default=True)),
                ('dvd_emprunteur_nom', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu_name', models.CharField(max_length=45)),
                ('jeu_createur', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre_name', models.CharField(max_length=45)),
                ('livre_auteur', models.CharField(max_length=45)),
                ('livre_dateEmprunt', models.DateField(blank=True, null=True)),
                ('livre_disponible', models.BooleanField(default=True)),
                ('livre_emprunteur_nom', models.CharField(max_length=45)),
            ],
        ),
    ]
