# Generated by Django 5.0.1 on 2024-02-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='cd_artiste',
            new_name='artiste',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='cd_dateEmprunt',
            new_name='dateEmprunt',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='cd_disponible',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='cd_emprunteur_nom',
            new_name='emprunteur_nom',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='cd_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dvd_dateEmprunt',
            new_name='dateEmprunt',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dvd_disponible',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dvd_emprunteur_nom',
            new_name='emprunteur_nom',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dvd_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dvd_realisateur',
            new_name='realisateur',
        ),
        migrations.RenameField(
            model_name='jeudeplateau',
            old_name='jeu_createur',
            new_name='createur',
        ),
        migrations.RenameField(
            model_name='jeudeplateau',
            old_name='jeu_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_auteur',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_dateEmprunt',
            new_name='dateEmprunt',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_disponible',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_emprunteur_nom',
            new_name='emprunteur_nom',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_name',
            new_name='name',
        ),
    ]
