# Generated by Django 5.0.1 on 2024-02-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_rename_cd_artiste_cd_artiste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emprunteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
