# Generated by Django 5.0.1 on 2024-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0005_emprunteur_remove_cd_emprunteur_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
        migrations.DeleteModel(
            name='CD',
        ),
        migrations.DeleteModel(
            name='DVD',
        ),
        migrations.DeleteModel(
            name='JeuDePlateau',
        ),
        migrations.DeleteModel(
            name='emprunteur',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
